server:
  port: 8030
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ##是否将当前服务的IP注册到eureka server
    prefer-ip-address: true
zuul:
  routes:
    provider: /p/**
##给服务提供者provider设置映射